import type { EventWithDetails } from "@/types";

const now = new Date();
const d = (daysFromNow: number, hour = 20) => {
  const dt = new Date(now);
  dt.setDate(dt.getDate() + daysFromNow);
  dt.setHours(hour, 0, 0, 0);
  return dt;
};

export const MOCK_EVENTS: EventWithDetails[] = [
  {
    id: "mock-1",
    slug: "bad-bunny-most-wanted-tour-quito-2025",
    title: "Bad Bunny: Most Wanted Tour",
    description:
      "El conejo malo llega a Ecuador en su gira más esperada. Una noche llena de reggaetón, trap y energía pura.",
    category: "CONCERT",
    status: "PUBLISHED",
    coverImageUrl: "/events/bad-bunny.jpg",
    bannerUrl: null,
    isOnline: false,
    onlineUrl: null,
    minAge: 18,
    publishedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    organizerId: "org-1",
    venueId: "venue-1",
    organizer: {
      id: "org-1",
      userId: "user-1",
      name: "Live Nation Ecuador",
      slug: "live-nation-ecuador",
      description: "Promotora de eventos internacionales",
      logoUrl: null,
      website: null,
      status: "APPROVED",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    venue: {
      id: "venue-1",
      name: "Estadio Olímpico Atahualpa",
      slug: "estadio-olimpico-atahualpa",
      address: "Av. 6 de Diciembre N52-247",
      city: "Quito",
      province: "Pichincha",
      country: "Ecuador",
      lat: -0.1865,
      lng: -78.4834,
      capacity: 40000,
      imageUrl: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    sessions: [
      {
        id: "sess-1",
        eventId: "mock-1",
        name: null,
        startAt: d(12, 20),
        endAt: d(12, 23),
        timezone: "America/Guayaquil",
        doorsOpenAt: d(12, 18),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    ticketTypes: [
      {
        id: "tt-1a",
        eventId: "mock-1",
        name: "General",
        description: null,
        price: 8500,
        capacity: 20000,
        reserved: 0,
        sold: 14200,
        maxPerOrder: 10,
        minPerOrder: 1,
        saleStartsAt: null,
        saleEndsAt: null,
        perks: [],
        sortOrder: 0,
        isVisible: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "tt-1b",
        eventId: "mock-1",
        name: "VIP",
        description: null,
        price: 18000,
        capacity: 2000,
        reserved: 0,
        sold: 1800,
        maxPerOrder: 4,
        minPerOrder: 1,
        saleStartsAt: null,
        saleEndsAt: null,
        perks: ["Meet & Greet", "Área exclusiva", "Bebida de bienvenida"],
        sortOrder: 1,
        isVisible: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: "mock-2",
    slug: "taylor-swift-eras-tour-guayaquil-2025",
    title: "Taylor Swift: The Eras Tour",
    description:
      "Un recorrido épico por todas las eras musicales de Taylor Swift. El espectáculo más grande del año llega a Guayaquil.",
    category: "CONCERT",
    status: "PUBLISHED",
    coverImageUrl: "/events/taylor-swift.jpg",
    bannerUrl: null,
    isOnline: false,
    onlineUrl: null,
    minAge: null,
    publishedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    organizerId: "org-1",
    venueId: "venue-2",
    organizer: {
      id: "org-1",
      userId: "user-1",
      name: "Live Nation Ecuador",
      slug: "live-nation-ecuador",
      description: null,
      logoUrl: null,
      website: null,
      status: "APPROVED",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    venue: {
      id: "venue-2",
      name: "Estadio Monumental Banco Pichincha",
      slug: "estadio-monumental",
      address: "Av. del Bombero",
      city: "Guayaquil",
      province: "Guayas",
      country: "Ecuador",
      lat: -2.1459,
      lng: -79.8949,
      capacity: 60000,
      imageUrl: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    sessions: [
      {
        id: "sess-2",
        eventId: "mock-2",
        name: null,
        startAt: d(18, 20),
        endAt: d(18, 23),
        timezone: "America/Guayaquil",
        doorsOpenAt: d(18, 17),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    ticketTypes: [
      {
        id: "tt-2a",
        eventId: "mock-2",
        name: "General",
        description: null,
        price: 9500,
        capacity: 30000,
        reserved: 0,
        sold: 28000,
        maxPerOrder: 8,
        minPerOrder: 1,
        saleStartsAt: null,
        saleEndsAt: null,
        perks: [],
        sortOrder: 0,
        isVisible: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "tt-2b",
        eventId: "mock-2",
        name: "Pit",
        description: null,
        price: 22000,
        capacity: 5000,
        reserved: 0,
        sold: 4800,
        maxPerOrder: 4,
        minPerOrder: 1,
        saleStartsAt: null,
        saleEndsAt: null,
        perks: ["Acceso al foso", "Vista privilegiada"],
        sortOrder: 1,
        isVisible: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: "mock-3",
    slug: "barcelona-sc-vs-liga-de-quito-clasico-2025",
    title: "Barcelona SC vs. LDU Quito — Clásico del Astillero",
    description:
      "El partido más esperado del fútbol ecuatoriano. Dos gigantes, una sola cancha. ¿Quién se lleva el clásico?",
    category: "SPORT",
    status: "PUBLISHED",
    coverImageUrl: "/events/barcelona-liga.jpg",
    bannerUrl: null,
    isOnline: false,
    onlineUrl: null,
    minAge: null,
    publishedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    organizerId: "org-2",
    venueId: "venue-2",
    organizer: {
      id: "org-2",
      userId: "user-2",
      name: "Barcelona Sporting Club",
      slug: "barcelona-sc",
      description: null,
      logoUrl: null,
      website: null,
      status: "APPROVED",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    venue: {
      id: "venue-2",
      name: "Estadio Monumental Banco Pichincha",
      slug: "estadio-monumental",
      address: "Av. del Bombero",
      city: "Guayaquil",
      province: "Guayas",
      country: "Ecuador",
      lat: -2.1459,
      lng: -79.8949,
      capacity: 60000,
      imageUrl: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    sessions: [
      {
        id: "sess-3",
        eventId: "mock-3",
        name: null,
        startAt: d(6, 17),
        endAt: d(6, 19),
        timezone: "America/Guayaquil",
        doorsOpenAt: d(6, 15),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    ticketTypes: [
      {
        id: "tt-3a",
        eventId: "mock-3",
        name: "General Norte",
        description: null,
        price: 1500,
        capacity: 15000,
        reserved: 0,
        sold: 10000,
        maxPerOrder: 10,
        minPerOrder: 1,
        saleStartsAt: null,
        saleEndsAt: null,
        perks: [],
        sortOrder: 0,
        isVisible: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "tt-3b",
        eventId: "mock-3",
        name: "Tribuna Preferencia",
        description: null,
        price: 3500,
        capacity: 10000,
        reserved: 0,
        sold: 7500,
        maxPerOrder: 8,
        minPerOrder: 1,
        saleStartsAt: null,
        saleEndsAt: null,
        perks: [],
        sortOrder: 1,
        isVisible: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "tt-3c",
        eventId: "mock-3",
        name: "Palco VIP",
        description: null,
        price: 12000,
        capacity: 500,
        reserved: 0,
        sold: 320,
        maxPerOrder: 4,
        minPerOrder: 1,
        saleStartsAt: null,
        saleEndsAt: null,
        perks: ["Palco privado", "Servicio de alimentos", "Parking incluido"],
        sortOrder: 2,
        isVisible: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: "mock-4",
    slug: "metallica-m72-world-tour-quito-2025",
    title: "Metallica: M72 World Tour",
    description:
      "La banda de metal más grande del mundo regresa. Dos noches épicas, dos setlists completamente diferentes. Quito, prepárate.",
    category: "CONCERT",
    status: "PUBLISHED",
    coverImageUrl: "/events/metallica.jpg",
    bannerUrl: null,
    isOnline: false,
    onlineUrl: null,
    minAge: 16,
    publishedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    organizerId: "org-1",
    venueId: "venue-1",
    organizer: {
      id: "org-1",
      userId: "user-1",
      name: "Live Nation Ecuador",
      slug: "live-nation-ecuador",
      description: null,
      logoUrl: null,
      website: null,
      status: "APPROVED",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    venue: {
      id: "venue-1",
      name: "Estadio Olímpico Atahualpa",
      slug: "estadio-olimpico-atahualpa",
      address: "Av. 6 de Diciembre N52-247",
      city: "Quito",
      province: "Pichincha",
      country: "Ecuador",
      lat: -0.1865,
      lng: -78.4834,
      capacity: 40000,
      imageUrl: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    sessions: [
      {
        id: "sess-4",
        eventId: "mock-4",
        name: "Noche 1",
        startAt: d(24, 20),
        endAt: d(24, 23),
        timezone: "America/Guayaquil",
        doorsOpenAt: d(24, 18),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    ticketTypes: [
      {
        id: "tt-4a",
        eventId: "mock-4",
        name: "General",
        description: null,
        price: 7500,
        capacity: 25000,
        reserved: 0,
        sold: 18000,
        maxPerOrder: 10,
        minPerOrder: 1,
        saleStartsAt: null,
        saleEndsAt: null,
        perks: [],
        sortOrder: 0,
        isVisible: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "tt-4b",
        eventId: "mock-4",
        name: "Floor",
        description: null,
        price: 13500,
        capacity: 5000,
        reserved: 0,
        sold: 4200,
        maxPerOrder: 6,
        minPerOrder: 1,
        saleStartsAt: null,
        saleEndsAt: null,
        perks: ["Acceso al piso principal"],
        sortOrder: 1,
        isVisible: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: "mock-5",
    slug: "emelec-vs-deportivo-cuenca-2025",
    title: "CS Emelec vs. Deportivo Cuenca",
    description:
      "Partido de LigaPro Serie A. El Bombillo recibe a la Máquina Galletera en el Estadio George Capwell.",
    category: "SPORT",
    status: "PUBLISHED",
    coverImageUrl: "/events/emelec.jpg",
    bannerUrl: null,
    isOnline: false,
    onlineUrl: null,
    minAge: null,
    publishedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    organizerId: "org-3",
    venueId: "venue-3",
    organizer: {
      id: "org-3",
      userId: "user-3",
      name: "Club Sport Emelec",
      slug: "cs-emelec",
      description: null,
      logoUrl: null,
      website: null,
      status: "APPROVED",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    venue: {
      id: "venue-3",
      name: "Estadio George Capwell",
      slug: "estadio-george-capwell",
      address: "Av. Quito y Calle 13",
      city: "Guayaquil",
      province: "Guayas",
      country: "Ecuador",
      lat: -2.1978,
      lng: -79.8834,
      capacity: 18000,
      imageUrl: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    sessions: [
      {
        id: "sess-5",
        eventId: "mock-5",
        name: null,
        startAt: d(3, 16),
        endAt: d(3, 18),
        timezone: "America/Guayaquil",
        doorsOpenAt: d(3, 14),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    ticketTypes: [
      {
        id: "tt-5a",
        eventId: "mock-5",
        name: "General Sur",
        description: null,
        price: 1200,
        capacity: 8000,
        reserved: 0,
        sold: 5500,
        maxPerOrder: 10,
        minPerOrder: 1,
        saleStartsAt: null,
        saleEndsAt: null,
        perks: [],
        sortOrder: 0,
        isVisible: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "tt-5b",
        eventId: "mock-5",
        name: "Tribuna",
        description: null,
        price: 2500,
        capacity: 6000,
        reserved: 0,
        sold: 3200,
        maxPerOrder: 8,
        minPerOrder: 1,
        saleStartsAt: null,
        saleEndsAt: null,
        perks: [],
        sortOrder: 1,
        isVisible: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: "mock-6",
    slug: "shakira-las-mujeres-ya-no-lloran-world-tour-quito",
    title: "Shakira: Las Mujeres Ya No Lloran World Tour",
    description:
      "La Loba regresa a Ecuador con su gira más personal y poderosa. Baila, canta y celebra con Shakira en Quito.",
    category: "CONCERT",
    status: "PUBLISHED",
    coverImageUrl: "/events/shakira.jpg",
    bannerUrl: null,
    isOnline: false,
    onlineUrl: null,
    minAge: null,
    publishedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    organizerId: "org-1",
    venueId: "venue-1",
    organizer: {
      id: "org-1",
      userId: "user-1",
      name: "Live Nation Ecuador",
      slug: "live-nation-ecuador",
      description: null,
      logoUrl: null,
      website: null,
      status: "APPROVED",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    venue: {
      id: "venue-1",
      name: "Estadio Olímpico Atahualpa",
      slug: "estadio-olimpico-atahualpa",
      address: "Av. 6 de Diciembre N52-247",
      city: "Quito",
      province: "Pichincha",
      country: "Ecuador",
      lat: -0.1865,
      lng: -78.4834,
      capacity: 40000,
      imageUrl: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    sessions: [
      {
        id: "sess-6",
        eventId: "mock-6",
        name: null,
        startAt: d(30, 21),
        endAt: d(30, 23),
        timezone: "America/Guayaquil",
        doorsOpenAt: d(30, 19),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    ticketTypes: [
      {
        id: "tt-6a",
        eventId: "mock-6",
        name: "General",
        description: null,
        price: 7000,
        capacity: 22000,
        reserved: 0,
        sold: 16000,
        maxPerOrder: 8,
        minPerOrder: 1,
        saleStartsAt: null,
        saleEndsAt: null,
        perks: [],
        sortOrder: 0,
        isVisible: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "tt-6b",
        eventId: "mock-6",
        name: "VIP Golden Circle",
        description: null,
        price: 20000,
        capacity: 3000,
        reserved: 0,
        sold: 2100,
        maxPerOrder: 4,
        minPerOrder: 1,
        saleStartsAt: null,
        saleEndsAt: null,
        perks: ["Área exclusiva frente al escenario", "Bar privado", "Merchandising"],
        sortOrder: 1,
        isVisible: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: "mock-7",
    slug: "ldu-quito-vs-independiente-del-valle-2025",
    title: "LDU Quito vs. Independiente del Valle",
    description:
      "El clásico serrano de la capital. LDU recibe al campeón de Sudamérica en el coloso de la Casa Blanca.",
    category: "SPORT",
    status: "PUBLISHED",
    coverImageUrl: "/events/barcelona-liga.jpg",
    bannerUrl: null,
    isOnline: false,
    onlineUrl: null,
    minAge: null,
    publishedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    organizerId: "org-4",
    venueId: "venue-4",
    organizer: {
      id: "org-4",
      userId: "user-4",
      name: "Liga Deportiva Universitaria",
      slug: "ldu-quito",
      description: null,
      logoUrl: null,
      website: null,
      status: "APPROVED",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    venue: {
      id: "venue-4",
      name: "Estadio Rodrigo Paz Delgado",
      slug: "estadio-rodrigo-paz",
      address: "Av. de la Prensa",
      city: "Quito",
      province: "Pichincha",
      country: "Ecuador",
      lat: -0.1097,
      lng: -78.4945,
      capacity: 41575,
      imageUrl: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    sessions: [
      {
        id: "sess-7",
        eventId: "mock-7",
        name: null,
        startAt: d(9, 15),
        endAt: d(9, 17),
        timezone: "America/Guayaquil",
        doorsOpenAt: d(9, 13),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    ticketTypes: [
      {
        id: "tt-7a",
        eventId: "mock-7",
        name: "General",
        description: null,
        price: 1800,
        capacity: 20000,
        reserved: 0,
        sold: 12000,
        maxPerOrder: 10,
        minPerOrder: 1,
        saleStartsAt: null,
        saleEndsAt: null,
        perks: [],
        sortOrder: 0,
        isVisible: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "tt-7b",
        eventId: "mock-7",
        name: "Preferencia",
        description: null,
        price: 4000,
        capacity: 8000,
        reserved: 0,
        sold: 5000,
        maxPerOrder: 6,
        minPerOrder: 1,
        saleStartsAt: null,
        saleEndsAt: null,
        perks: [],
        sortOrder: 1,
        isVisible: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: "mock-8",
    slug: "coldplay-music-of-the-spheres-guayaquil-2025",
    title: "Coldplay: Music of the Spheres World Tour",
    description:
      "El espectáculo de luces y colores más impresionante del mundo. Coldplay llega a Guayaquil con su gira récord.",
    category: "CONCERT",
    status: "PUBLISHED",
    coverImageUrl: "/events/coldplay.jpg",
    bannerUrl: null,
    isOnline: false,
    onlineUrl: null,
    minAge: null,
    publishedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    organizerId: "org-1",
    venueId: "venue-2",
    organizer: {
      id: "org-1",
      userId: "user-1",
      name: "Live Nation Ecuador",
      slug: "live-nation-ecuador",
      description: null,
      logoUrl: null,
      website: null,
      status: "APPROVED",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    venue: {
      id: "venue-2",
      name: "Estadio Monumental Banco Pichincha",
      slug: "estadio-monumental",
      address: "Av. del Bombero",
      city: "Guayaquil",
      province: "Guayas",
      country: "Ecuador",
      lat: -2.1459,
      lng: -79.8949,
      capacity: 60000,
      imageUrl: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    sessions: [
      {
        id: "sess-8",
        eventId: "mock-8",
        name: null,
        startAt: d(45, 21),
        endAt: d(45, 23),
        timezone: "America/Guayaquil",
        doorsOpenAt: d(45, 19),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    ticketTypes: [
      {
        id: "tt-8a",
        eventId: "mock-8",
        name: "General",
        description: null,
        price: 8000,
        capacity: 35000,
        reserved: 0,
        sold: 30000,
        maxPerOrder: 8,
        minPerOrder: 1,
        saleStartsAt: null,
        saleEndsAt: null,
        perks: [],
        sortOrder: 0,
        isVisible: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "tt-8b",
        eventId: "mock-8",
        name: "VIP Infinity Stage",
        description: null,
        price: 25000,
        capacity: 4000,
        reserved: 0,
        sold: 3600,
        maxPerOrder: 4,
        minPerOrder: 1,
        saleStartsAt: null,
        saleEndsAt: null,
        perks: ["360° stage access", "LED wristband kit", "Cocktail de bienvenida"],
        sortOrder: 1,
        isVisible: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
];
